;;; TODO:
;;; at the moment caught in outer block
;;; SHOULD BE CAUGHT IN INNER BLOCK

(try
 (block get-out
   (try
    (finally
     (progn
      (write "in the block, and returning")
      (return-from get-out)
      )
     (throw "finally - where is this caught?"))
   (write "caught in inner block")))
 (write "caught in outer block"))

(write "outside the block now")
(throw "and lets see now, where this jumps")  ;; this did segfault. doesn't anymore
